compile_click:
  image: clickable/ubuntu-sdk:16.04-armhf
  before_script:
    - pip install ssh://git@github.com:mjsir911/clickable.git
    - npm install -g --unsafe-perm cordova@7.0.0
  script: 
    - clickable --container-mode build
    - clickable --container-mode click-build

